### ISSUE TITLE
Write to `:messages`

### ISSUE THREAD

**Issue by lostl1ght** [vigoux/notifier.nvim#12]
Kind of related to #11.

By default `vim.notify` writes to `:messages` as well, so users can use `:messages` or something like [tpope/vim-scriptease](https://github.com/tpope/vim-scriptease) to read notifications again. However, `vim.notify` uses `nvim_echo` to display messages and write to `:messages`, so if `nvim_echo` is used to write to `:messages` messages will be duplicated.

Is there a way to write to `:messages` directly?

**Comment by lostl1ght** [comment]
I'd like to note that I'm aware of `NotifierReplay`. But if this feature is excessive then we get back to #11.

**Comment by vigoux** [comment]
I think it is excessive: the API design of `vim.notify` is geared towards a default implementation calling out to `messages` and others doing somehow else.

What we'd need is actual replay support.

**Comment by lostl1ght** [comment]
I see, I'm closing this as unplanned then.
