### ISSUE TITLE
Error with notifier.nvim after updating to 3c9f8a82c53bdae2366db153150fbe5551ff32cc and newer

### ISSUE THREAD

**Issue by megalithic** [vigoux/notifier.nvim#15]
https://github.com/vigoux/notifier.nvim/blob/3ecc25928027dc08a83f308723d85eddb2651884/lua/notifier/init.lua#L15

<img width="1720" alt="image" src="https://user-images.githubusercontent.com/3678/192794912-d4f1d4e7-cb85-426c-abfe-d4804b0df96a.png">

**Comment by megalithic** [comment]
LOVE this so much btw, i can't wait for an open api to tie into this plugin from other things.

**Comment by vigoux** [comment]
That's weird ?

Do you have an idea of what walls `vim.notify` ? It seems that it does not call it correctly...

Thanks for the kind words ! I am planning to write the docs for the status API soon-ish, to allow people to add things !

**Comment by megalithic** [comment]
> That's weird ?
> 
> Do you have an idea of what walls `vim.notify` ? It seems that it does not call it correctly...
> 
> Thanks for the kind words ! I am planning to write the docs for the status API soon-ish, to allow people to add things !

That's great to hear!

I've got `vim.notify` being called upon `User PackerCompileDone` autocmd.

EDIT: 🤦 i was passing simply "info" to `vim.notify`'s log level arg; changing THAT to vim.log.levels.INFO (or just leaving blank since the default minimum log level for notifier.nvim is INFO anyway).

Fixed; and apologies for the noise.

**Comment by vigoux** [comment]
No worries, might be worth to check in the code anyway, I think that this kind of mistake is not that rare.

**Comment by megalithic** [comment]
@vigoux; ironically, i'm getting this issue from other plugins that use a string representation of the log level, e.g. "ERROR", for instance, instead of `vim.log.levels.ERROR`.

Any chance of addressing this?

**Comment by vigoux** [comment]
Honestly, that's just the plugin using the API wrong.

You should open an issue on the plugin that does that.

**Comment by megalithic** [comment]
Thanks @vigoux; I'm referencing this here: https://github.com/rcarriga/nvim-dap-ui/pull/159
