### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by megalithic** [vigoux/notifier.nvim#16]
I typically send things down to locationlist/quickfix; i use tpope's scripttease to send `:messages` down there via `:Messages`; I'd _love_ to be able to replay notifier entries down to the quickfixlist.

Thoughts?

**Comment by vigoux** [comment]
Hi!

First of all, for now the only things one can replay are `vim.notify` ones.

Appart from that, it seems perfectly feasible to add such a things, something like `NotifierReplay!`

**Comment by vigoux** [comment]
Hi this should have been added in latest master, could you confirm this is the case ?

**Comment by vigoux** [comment]
Sorry for the delay by the way !

**Comment by megalithic** [comment]
ROCKSTAR! thanks @vigoux ! testing now. ❤️

**Comment by megalithic** [comment]
This does it! thanks again @vigoux

**Comment by vigoux** [comment]
Great! Feel free to report anything bothering you with the plugin , and thanks for your contribution!
