### ISSUE TITLE
Error message at startup

### ISSUE THREAD

**Issue by arafatamim** [vigoux/notifier.nvim#2]
```
E5108: Error executing lua .../pack/packer/start/notifier.nvim/lua/notifier/config.lua:70: 'bg' is not a valid color
```
Error occurs on Neovim `v0.7.2` & `v0.8.0-dev-973-g253f0ffd8`

**Comment by vigoux** [comment]
Hi, I just fixed this in 828f9be96170a4d8af2fc2a2136f22a0296b712e, could you confirm that this is fixed on your end too ?

(@phaazon I think that you might be interested in this too)

**Comment by hadronized** [comment]
Fixed on my side.

**Comment by arafatamim** [comment]
Yes, it works on `v0.7.2` but not on latest canary (same error, `v0.8.0-dev-973-g253f0ffd8`)

**Comment by vigoux** [comment]
Pretty weird then... I am not sure why that is, but that may be because of some super-nightly feature I assumed available.
In any case, if it works of 0.7.2 it is already good, 0.8 is nightly and kind of expected to break.

**Comment by arafatamim** [comment]
I agree. I assume I can close this issue then.

**Comment by vigoux** [comment]
I'd like to see if we can still fix this issue.
Did you try updating to the very latest master and see if it works?

**Comment by williamboman** [comment]
I've struggled with this as well. To me it seems like `nvim_set_hl` doesn't support the `bg`, `fg`, `background`, `foreground` values? There's [this comment as well](https://github.com/neovim/neovim/blob/92bc11a891538e5c306915bffef437f097572d09/src/nvim/highlight.c#L1066) which suggest the same.

This test fails upstream:

```diff
diff --git a/test/functional/api/highlight_spec.lua b/test/functional/api/highlight_spec.lua
index 2730f7e23..76719b7cc 100644
--- a/test/functional/api/highlight_spec.lua
+++ b/test/functional/api/highlight_spec.lua
@@ -354,4 +354,18 @@ describe("API: set highlight", function()
     meths.set_hl(0, 'Normal', {fg='#000083', bg='#0000F3'})
     eq({foreground = 131, background = 243}, nvim("get_hl_by_name", 'Normal', true))
   end)
+
+  it ("accepts special color names", function ()
+    for _, fg_val in ipairs{ 'fg', 'FG', 'foreground' } do
+      meths.set_hl(0, 'Test_hl1', {fg = fg_val})
+      eq('Test_hl1       xxx guifg=fg',
+        exec_capture('highlight Test_hl1'))
+    end
+
+    for _, fg_val in ipairs{ 'bg', 'BG', 'background' } do
+      meths.set_hl(0, 'Test_hl2', {fg = fg_val})
+      eq('Test_hl2       xxx guibg=bg',
+        exec_capture('highlight Test_hl2'))
+    end
+  end)
 end)
```

**Comment by vigoux** [comment]
It is a bit weird: using `NVIM v0.8.0-dev-985-gf9c183c0c` (latest commit at the time of writing) I get no errors, which suggests that this issue should be fixed.

**Comment by williamboman** [comment]
Ah let me try, I'm on the ancient version `NVIM v0.8.0-dev-977-g92bc11a89` 😛 

edit: Nope, same issue. The test above fails with the following message btw (which is the same as I get when setting up notifier):

```
DBG 2022-08-30T12:44:25.223 T12.57710.0 RPC: ch 1: invoke nvim_set_hl
DBG 2022-08-30T12:44:25.223 T12.57710.0 log_server_msg:687: RPC ->ch 1: [response] [1, 0, [1, "'fg' is not a valid color"], nil]
```

**Comment by vigoux** [comment]
Now _that's_ really weird...

**Comment by vigoux** [comment]
What happens if you run:
```lua
vim.api.nvim_set_hl(0, "NormalFloat", { fg = 'fg' })
```

**Comment by vigoux** [comment]
For the record, this _should_ be supported in latest master, but seems to have a pretty strange behavior:
https://github.com/neovim/neovim/blob/f9c183c0cad95f0370067e849af6bdbada7b6517/src/nvim/highlight_group.c#L2858

**Comment by williamboman** [comment]
So calling `nvim_set_hl` like that works fine. The error I'm getting is exactly this:

```diff
diff --git a/lua/notifier/config.lua b/lua/notifier/config.lua
index 3c9f71f..705eb6c 100644
--- a/lua/notifier/config.lua
+++ b/lua/notifier/config.lua
@@ -67,6 +67,8 @@ ConfigModule.HL_CONTENT = hl_group("Content", { link = "Normal", default = true
 ConfigModule.HL_TITLE = hl_group("Title", { link = "Title", default = true })
 
 
-vim.api.nvim_set_hl(ConfigModule.NS_ID, "NormalFloat", { bg = "bg" })
+vim.pretty_print(pcall(function ()
+   vim.api.nvim_set_hl(ConfigModule.NS_ID, "NormalFloat", { bg = "bg" })
+end))
 
 return ConfigModule
```

yields this message

```
false    ".../pack/packer/start/notifier.nvim/lua/notifier/config.lua:74: 'bg' is not a valid color"
```

I think I found the issue though - if I move my setup script from `plugin/notifier.lua` to `after/plugin/notifier.lua`, the error disappears and it executes just fine.

**Comment by vigoux** [comment]
> I think I found the issue though - if I move my setup script from `plugin/notifier.lua` to `after/plugin/notifier.lua`, the error disappears and it executes just fine.

That's a little weird... That would mean that some things are not set when loading the plugin (and especially part of the runtime ?). I'll open an issue upstream (neovim/neovim) with a (somewhat) more concise report for this issue.

EDIT: [the opened issue](https://github.com/neovim/neovim/issues/20008)

**Comment by vigoux** [comment]
So, I am afraid that there is not really a way to fix this issue, as this seems to be related to the order in which your plugins are loaded:
This function call will fail if the `Normal` group does not exist, and that's not the case by default (`nvim --clean`) and it is set by your colorscheme.

The fix I'll do will just avoid the error, but not actually solve it (it will just not call this function).

**Comment by vigoux** [comment]
Should have been definitely fixed in the end, could you confirm it is the case ?
The related issue is not relevant anymore, but it looks like we fell into one of those weird vim quirks.

**Comment by williamboman** [comment]
Ah, interesting. 6ea6a0a fixes the initial setup issue for me.
