### ISSUE TITLE
content alignment and line wrapping

### ISSUE THREAD

**Issue by bstaint** [vigoux/notifier.nvim#21]
![x](https://user-images.githubusercontent.com/5853792/194971853-5b2cec5e-1c33-4d07-b5e4-37e763555d2b.png)

**Comment by vigoux** [comment]
Well, I am not sure what you want this to look like ?

There's line wrapping, and that's a feature that has been requested in #11 

Please add the expected behavior, or I'll just close this issue.

**Comment by bstaint** [comment]
Multiple messages do not remain aligned

**Comment by vigoux** [comment]
That's because your window width is too small

**Comment by bstaint** [comment]
Tks answer
