### ISSUE TITLE
Allow to replace notifications belonging to the same group

### ISSUE THREAD

**Issue by pwntester** [vigoux/notifier.nvim#22]
Hi @vigoux 

I was wondering, if you could add support to enable message replacement for the nvim component as you have for the lsp one.

I locally modify `init.lua` replacing:

```lua
status.push("nvim", { mandat = msg, title = opts.title, icon = opts.icon })
```

with

```lua
    if opts.group and opts.done then
      status.pop("lsp", opts.group)
    elseif opts.group then
      status.push("lsp", { mandat = msg, title = opts.title, dim = true }, opts.group)
    else
      status.push("nvim", { mandat = msg, title = opts.title, icon = opts.icon })
    end
```

So I can group notifications using `vim.notify(msg, level, { group = "foo" }`. Sorry, for not sending a PR but havent used Teal ever :( Also, I was not sure you were ok with this change. 

Thanks for yet another great neovim contribution!

**Comment by vigoux** [comment]
Hi and thanks for that detailed suggestion!

I have a question though : I am not sure to see what the behavior should be.
Looking at the code it seems that you want to customize the notify implementation to include some lsp features?

Do you have a screenshot / video of your implementation?

**Comment by pwntester** [comment]
Im using it for my [CodeQL.nvim plugin](https://github.com/pwntester/codeql.nvim). The idea is to group all the scan progress notifications so that they use the same notification window and do not take the whole screen. CodeQL.nvim users will be able to choose any `vim.notify` backend, but if the backend supports grouping notifcations via a custom `vim.notify` option (`group`), the notifications will be more eye candy. 
![Recording 2022-10-14 at 08 56 05](https://user-images.githubusercontent.com/125701/195782782-dfb1f8c5-b345-45de-b5bf-c6452e3ec72a.gif)

**Comment by vigoux** [comment]
So, my problem is that mixing "replaceable" and "push" notifications under the same component is not actually well-defined yet.

What I can do is ensure that this works fine (and fix the bugs along the way), and report back to this issue.

In any case, the name of the component (here `nvim`), will stay the same (as I don't want to mix things around).

For a more flexible interface, I'd really recommend using the `status.push` / `status.pop` API.

**Comment by pwntester** [comment]
> For a more flexible interface, I'd really recommend using the status.push / status.pop API.

You are right, I should have probably used this from the beginning, thanks!

**Comment by pwntester** [comment]
Actually, it would be nice if you could install notifier as an LSP progress handler (`vim.lsp.handlers["$/progress"]  = function(err, msg, ctx) ...` so that CodeQL.nvim or any non-LSP plugin wanting to use the LSP progress notification system, can just gran the handler from `vim.lsp.handlers["$/progress"]` and invoke it.

Something similar to what `fidget.nvim` does [here](https://github.com/j-hui/fidget.nvim/blob/main/lua/fidget.lua#L516-L524)

**Comment by vigoux** [comment]
Notifier actually also does that though: https://github.com/vigoux/notifier.nvim/blob/afc9bf7ef8c31cfc716a2b849c34943a9788508b/teal/notifier/init.tl#L83-L96

**Comment by pwntester** [comment]
Thanks! So instead of replacing the handler, you are just "subscribing" to its messages and then process them?
[This](https://github.com/pwntester/codeql.nvim/commit/0cb389847cf16b9742bf1829bfe50381bdab390e) actually works with notifier.nvim and it should also work with other LSP progress handlers. Thanks for the help!

**Comment by vigoux** [comment]
I am not a LSP expert but I think that calling back to `$/progress` is better.

I wonder why your lsp does not do it by default though.

**Comment by pwntester** [comment]
CodeQL.nvim works with two servers, the LSP server (which correctly notifies progress through the LSP handler) and the Query server (in charge of running the CodeQL queries). This second server does not use the LSP handler to notify the query execution progress. What I did in that commit is to report the Query server progress using the LSP handler and use the same LSP client Id as the CodeQL LSP server.

Thanks a lot for the help!

**Comment by vigoux** [comment]
Not sure I understand that LSP-fu, but I am glad we sorted that out!
