### ISSUE TITLE
Can't quit because of unwritten buffer

### ISSUE THREAD

**Issue by gegoune** [vigoux/notifier.nvim#29]
Hi,

I need to apologise for vague issue, I am not able to replicate it as it only happens now and then. I am not sure what causes it but sometimes when I try to quit nvim with `:wqa` I get an error saying that `[No name]` buffer is modified and not saved preventing nvim from quitting. When I open buffer mentioned in error message I can see its content being one of messages that were displayed in notifier.nvim's window.

Did you ever come across it? Any idea how I could try to replicate it and provide you with more details?

Thanks!

**Comment by vigoux** [comment]
I never came accross it, and it feels weird to me.

Notifier should never write at any other place than its own buffer, so I can't really tell what's going on without a more precise guidance, sorry...

I'm going to close that for lack of repro steps.
