### ISSUE TITLE
Disable null ls notifications

### ISSUE THREAD

**Issue by halshar** [vigoux/notifier.nvim#30]
Hello,

Is there way to disable null-ls(none-ls) notifications? The plugin triggers when formatting a file and I want to disable/ignore everything related to null-ls. Currently my setup is as follows
```lua
require("notifier").setup({
  components = { "lsp" },
})
```

**Comment by tdjordan** [comment]
```lua
require("notifier").setup({
  ignore_messages = { "null_ls" },
  components = { "lsp" },
})
```

**Comment by halshar** [comment]
thank you :)
