### ISSUE TITLE
Truncating senders name

### ISSUE THREAD

**Issue by gegoune** [vigoux/notifier.nvim#7]
Hi there. I have noticed that sender name gets truncated, for example I will see `sumneko_lu`, but would like to see the whole string. How could I achieve that?

Thanks!

**Comment by vigoux** [comment]
Hi, it is strange that the sender name gets truncated, could you give me a sample of your setup so that I can try that too ?

**Comment by gegoune** [comment]
Not at the computer right now but I was calling setup without any arguments. 

But what I noticed was that calling vim.notify() with some long sender name resulted with full name printed out, so pretty weird why sumneko_lua would get cut off, also treesitter updating parsers send message with sender ended up cut off. 

How could I help you figuring out why that is?

**Comment by vigoux** [comment]
Maybe try to call `vim.notify` in such a way that the issue is reproduced.

**Comment by gegoune** [comment]
```
lua vim.notify('test', vim.log.levels.INFO, { title = 'sumneko_lua', icon = 'A' })
```
results in:

<img width="164" alt="Screenshot 2022-09-02 at 19 20 29" src="https://user-images.githubusercontent.com/69750637/188205834-d44c2107-b732-42f5-8ef4-67d947a17749.png">

Is that helpful?

**Comment by vigoux** [comment]
I'll try that out and see if I can reproduce it!

**Comment by williamboman** [comment]
Hey! I ran into this as well and fixed it locally, forgot to open a PR (did so now #9). I assume you're running satellite.nvim @gegoune?

**Comment by gegoune** [comment]
I do indeed, completely forgot about that. Thanks for the pr, will test it later. 

Edit: can confirm #9 fixes the issue.
Apologies @vigoux for poor issue; thanks @williamboman for miraculously figuring out what the issue is.
